### ISSUE TITLE
Support easy "latest nightly" version

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/setup-dafny-action#12]
i.e. something like this would just use the latest nightly release:

```yaml
- name: Set up Dafny
  uses: dafny-lang/setup-dafny-action@v1
  with:
    dafny-version: "nightly"
```
